# Generated by Django 5.1.7 on 2025-03-08 20:18

import datetime
import django.contrib.auth.models
import django.db.models.deletion
import misterx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task",
                    models.TextField(
                        help_text="The task that has to be solved", verbose_name="Task"
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(
                        help_text="How many points will be awarded for completing this task",
                        verbose_name="Points",
                    ),
                ),
                (
                    "solution",
                    models.TextField(
                        blank=True,
                        help_text="Solution for this task",
                        null=True,
                        verbose_name="Solution",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerGroup",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.group",),
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default=misterx.models.get_default_game_name,
                        max_length=255,
                        verbose_name="Name of Task Set",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Date of the game"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this game is active. Only one game can be active at the same time, setting this will override the value of the currently active model",
                        verbose_name="Active",
                    ),
                ),
                (
                    "tasks",
                    models.ManyToManyField(
                        blank=True, related_name="games", to="misterx.task"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="games", to="misterx.playergroup"
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Time of submission"
                    ),
                ),
                (
                    "accepted",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Whether the solution was accepted",
                    ),
                ),
                (
                    "points_override",
                    models.PositiveIntegerField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Override number of granted points",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="Further explanations you might want to add",
                        null=True,
                        verbose_name="Explanation",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="misterx.game",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="misterx.task",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="misterx.playergroup",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["task"], name="misterx_submission_task_idx"),
                    models.Index(fields=["-time"], name="misterx_submission_time_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("active",),
                name="unique_active",
                violation_error_message="There is an active game already.",
            ),
        ),
    ]
