# Generated by Django 5.1.7 on 2025-03-22 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misterx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='misterx.player'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='accepted',
            field=models.BooleanField(blank=True, default=None, help_text='Whether the solution was accepted', null=True, verbose_name='Accepted'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='points_override',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Override the number of points the group will receive for this submission', null=True, verbose_name='Granted points'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.DateTimeField(auto_now=True, help_text='Time of submission', verbose_name='Time'),
        ),
    ]
