# Generated by Django 5.1.7 on 2025-03-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misterx', '0002_submission_submitter_alter_submission_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='points_override',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Override the number of points the group will receive for this submission', null=True, verbose_name='Granted points override'),
        ),
    ]
