# Generated by Django 5.1.7 on 2025-03-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misterx', '0004_orderedtask_alter_game_tasks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderedtask',
            options={'ordering': ['task_number']},
        ),
        migrations.AddConstraint(
            model_name='orderedtask',
            constraint=models.UniqueConstraint(fields=('task', 'game'), name='unique_game_task_associations'),
        ),
    ]
