# Generated by Django 5.1.7 on 2025-04-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misterx', '0005_alter_orderedtask_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='feedback',
            field=models.TextField(blank=True, help_text="Optional Feedback on why this wasn't accepted", null=True, verbose_name='Feedback'),
        ),
    ]
