# Generated by Django 5.1.7 on 2025-04-03 21:48

import django.db.models.deletion
import misterx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misterx', '0006_submission_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=misterx.models.get_upload_path, verbose_name='File')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='misterx.submission')),
            ],
        ),
    ]
