# Generated by Django 5.1.7 on 2025-04-04 00:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misterx', '0007_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID for upload'),
        ),
    ]
